import { UserProvider } from '@/context/UserContext';
import './globals.css'
import Navbar from './navbar';
import Footer from './footer';

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang='en'>
      <body>
        <UserProvider>
          <Navbar />
          <div className='custom-container'>
            {children}
          </div>
          <Footer />
        </UserProvider>
      </body>
    </html>
  )
}
